### PR TITLE
Extension Search bar implementation

### PR DESCRIPTION
**Pull request by Kabiirk**
Hi @tomlin7 ,

This closes Issue #409.

I've opted for a simple search logic that returns exact matches. Also searching for an empty string would give you the complete (initial) string as well.

Search feature can be triggered either by pressing the `SEARCH` icon in the top right (beside the `REFRESH` icon), or by pressing `<ENTER>` key after typing.

### CODE REVIEW

**Review by tomlin7 — APPROVED** [review]
Code looks very clean! tested the feature and works well

**Comment by Kabiirk** [comment]
Thanks ! Good to know

**Comment by tomlin7** [comment]
@Kabiirk happy hacktoberfest! ❤️

**Comment by Kabiirk** [comment]
@tomlin7 
Happy Hacktoberfest to you too ! ❤️

**Pull request merged**
