### PR TITLE
Added a session restore functionality

### LINKED ISSUE #392: Saving most recent sessions to local
## Feature
Saving most recent session to local storage and then providing an option to restore the session on next startup.
Or even restoring that session automatically (though I think former suits best)

### PR DESCRIPTION
**Pull request by RINO-GAELICO**
Hi,

I've started drafting the session-saving feature and would appreciate some guidance.

So far, I've stored the opened files and directories in a session table with two columns (`file_path` and `folder_path`). Currently, I'm working on the helper functions `_get_opened_files()` and `_get_opened_directories()`.

I have a couple of questions:

1. Is my implementation of `_get_opened_files()` correct?
2. Where can I find the list of currently opened directories for `_get_opened_directories()`?

Thanks in advance for your help!

Fixes #392

### CODE REVIEW

**Review by tomlin7 — CHANGES_REQUESTED** [review]
@RINO-GAELICO Since this is an entire new functionality, I suggest moving these methods to a separate src/biscuit/sessions.py that may contain a `SessionManager` class, and then keep an instance of that attached in the [ConfigManager](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/config.py#L54). 

For reference, see the [HistoryManager](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/history.py)

**Comment by tomlin7** [comment]
@RINO-GAELICO Pardon, I did not notice the questions, implementation for getting opened files is correct. And I don't think you will need to get opened directories for now, as #317 is not added yet there will only be one directory open at a time, just save the active directory `self.base.active_directory`

**Comment by RINO-GAELICO** [comment]
Sorry it took me a while to get back to work on this project. 
I hope the latest changes reflect your recommendations and provide a better implementation of the functionality.

**Review by tomlin7 — APPROVED** [review]
@RINO-GAELICO The ConfigManager, EventManager, and GUIManager altogether constitute the main App class (`base` class of all other components). You were trying to access `base` from the base itself xd.

although it's my bad as well, documenting process is not done yet. I have added an option to restore the session as well, check the welcome tab of editor.

Thanks for the contribution, happy hacktoberfest <3

**Pull request merged**
