### PR TITLE
docs: Added Arch Linux commands to contributing guideline and various minor changes

### PR DESCRIPTION
**Pull request by shirsakm**
I have added the commands to be run on Arch Linux for setting up the project when contributing, and other minor changes.

Here is a list of the changes I have made,
#### Added a step to add a virtual environment
I find this to be an important step as otherwise there could be dependency conflicts which would result in issues being opened, which are unrelated to the project completely. Moreover, it can be hard to diagnose sometimes.
#### Moved the important note above the `poetry install` step
The system packages have to be installed before, and having it afterwards can result in it being missed.
#### Added `$` in front of the commands
It is the standard way to represent a bash prompt, and helps distinguish the various commands, improving readability.
#### Moved the Python version requirement into a note.

Please let me know if there are any issues, or any edits that go against the formatting guidelines.

### CODE REVIEW

**Comment by shirsakm** [comment]
Implements the changes as mentioned in #408

**Comment by shirsakm** [comment]
Btw, I believe a tag needs to be added for this PR to count towards Hacktoberfest.

**Comment by shirsakm** [comment]
Just wanted to mention, was the including of the code blocks in the code blocks intended?
Also, the usage of `!!!` instead of `[!NOTE]` is certainly an interesting choice, any particular reasons for the change?

And could you add the `hacktoberfest-accepted` label to the PR?

Thanks!

**Comment by tomlin7** [comment]
@shirsakm you might've noticed the mkdocs config in the root directory, `/docs/` is deployed using mkdocs here: https://tomlin7.github.io/biscuit/

**Pull request merged**
